# Module 1
Tensors are specialized data structures that are very similar to arrays and matrices. We will use tensors to encode the inputs and outputs of a model, as well as the model's parameters.

Tensors are similar to Numpy's ndarrays, except tensors can run on GPUs or other specialized hardware to accelerate computing.

In [1]:
import torch
import numpy as np

Tensors can be initialized in various ways:
- Directly from data
- From a NumPy array
- From another tensor
- With random or constant values

In [6]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

print(x_data)

tensor([[1, 2],
        [3, 4]])


In [8]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(x_np)

tensor([[1, 2],
        [3, 4]])


In [5]:
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)

print(x_ones)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.6329, 0.6959],
        [0.7710, 0.7080]])


In [9]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.1881, 0.9634, 0.0495],
        [0.3696, 0.5629, 0.3127]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
