# Module 1 - Tensors
Tensors are specialized data structures that are very similar to arrays and matrices. We will use tensors to encode the inputs and outputs of a model, as well as the model's parameters.

Tensors are similar to Numpy's ndarrays, except tensors can run on GPUs or other specialized hardware to accelerate computing.

## Tensor Initialization

In [1]:
import torch
import numpy as np

Tensors can be initialized in various ways:
- Directly from data
- From a NumPy array
- From another tensor
- With random or constant values

In [6]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

print(x_data)

tensor([[1, 2],
        [3, 4]])


In [8]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(x_np)

tensor([[1, 2],
        [3, 4]])


In [5]:
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)

print(x_ones)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.6329, 0.6959],
        [0.7710, 0.7080]])


In [9]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.1881, 0.9634, 0.0495],
        [0.3696, 0.5629, 0.3127]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Tensor Attributes

Tensor attributes describe their shape, datatype, and the device on which they are stored:

In [10]:
tensor = torch.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


## Tensor Operations
Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, here: https://pytorch.org/docs/stable/torch.html
Each can be run on GPU (higher speeds than CPU)

In [28]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(tensor.device)
if not torch.backends.mps.is_available():
    if not torch.backends.mps.is_built():
        print("MPS not available because the current PyTorch install was not "
              "built with MPS enabled.")
    else:
        print("MPS not available because the current MacOS version is not 12.3+ "
              "and/or you do not have an MPS-enabled device on this machine.")
else:
    mps_device = torch.device("mps")
    torch.set_default_device(mps_device)
    print(tensor.device)

mps:0


Standard numpy-like indexing and slicing:

In [30]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='mps:0')
mps:0


In [35]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]], device='mps:0')
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='mps:0')


In [38]:
tensor.mul(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='mps:0')

In [39]:
tensor * tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='mps:0')

In [40]:
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='mps:0')

In [41]:
tensor @ tensor.T

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='mps:0')

In [45]:
#In place operations have a _ suffix

#In place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history.
tensor.add_(5)

tensor([[21., 20., 21., 21.],
        [21., 20., 21., 21.],
        [21., 20., 21., 21.],
        [21., 20., 21., 21.]], device='mps:0')

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other:

In [50]:
t = torch.ones(5, device="cpu")
print(t)
n = t.numpy()
print(t)

t.add_(1)
print(t)
print(n)


tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
